#!/usr/bin/env bash
# Build the static replay for Vercel and stage it for a prebuilt deploy.
#
# Vercel CANNOT build this from git. The basemap, the approach-lamp geometry
# and the recorded traces are all gitignored generated artefacts -- a remote
# build would check out the repo, find none of them, and publish a page whose
# traffic layer silently never arrives. So the build happens here, where those
# files exist, and only the finished directory is uploaded.
#
# Vercel also cannot run the live simulation, for the same reason GitHub Pages
# cannot: SUMO needs a persistent process holding a 30 MB network, and
# serverless functions are stateless, time-limited and do not hold WebSockets.
# What deploys is the recording.
#
#   bash sim/build_vercel.sh          # build + stage
#   vercel deploy --prod web/dist-vercel
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/web/dist-vercel"

for f in web/public/data/basemap_barcelona.png web/public/replay/manifest.json; do
  [ -f "$ROOT/$f" ] || { echo "[abort] missing $f — run sim/bake_replay.py first"; exit 1; }
done

cd "$ROOT/web"
# --base=./ , not --base=/ . Under Git Bash the MSYS layer rewrites a bare "/"
# into the shell's Windows root, and the build silently emits asset paths like
# /Users/User/AppData/Local/hermes/git/assets/... which 404 everywhere. A
# relative base avoids the translation and works at any mount point.
VITE_REPLAY_ONLY=1 npx vite build --base=./ --outDir dist-vercel

# Keep only what the replay fetches. The rest belongs to the three.js scene and
# would trebled the upload for nothing.
cd "$OUT/data"
ls | grep -vE '^(basemap_barcelona\.(png|json)|signal_approaches\.geojson)$' \
  | while read -r f; do rm -rf "$f"; done

# Long-lived caching: every asset here is content-hashed or regenerated by a
# named script, so nothing is edited in place.
cat > "$OUT/vercel.json" <<'JSON'
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "headers": [
    { "source": "/(data|replay|assets)/(.*)",
      "headers": [{ "key": "Cache-Control",
                    "value": "public, max-age=31536000, immutable" }] }
  ]
}
JSON

echo
echo "[ok] staged $(du -sh "$OUT" | cut -f1) in web/dist-vercel"
echo "     deploy with:  vercel deploy --prod web/dist-vercel"
